apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: ghcr.io/immich-app/immich-charts
      chart: immich
      targetRevision: '*'
      helm:
        valueFiles:
          - $values/apps/immich/base/values.yaml
        parameters:
          - name: immich.persistence.library.existingClaim
            value: immich-library
          - name: valkey.enabled
            value: "true"
          - name: controllers.main.containers.main.image.tag
            value: v2.2.3
    
    - repoURL: git@github.com:soeguet/homelab.git
      targetRevision: HEAD
      path: apps/immich/base
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
