apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: ghcr.io/immich-app/immich-charts
      chart: immich
      targetRevision: '*'
      helm:
        parameters:
          - name: immich.persistence.library.existingClaim
            value: immich-library
          - name: valkey.enabled
            value: "true"
          - name: controllers.main.containers.main.image.tag
            value: v2.2.3
          - name: IMMICH_IGNORE_MOUNT_CHECK_ERRORS
            value: "true"
          - name: env.DB_HOSTNAME
            value: immich-postgresql
          - name: env.DB_PORT
            value: "5432"
          - name: env.DB_DATABASE_NAME
            value: immich
          - name: env.DB_USERNAME
            value: postgres
          - name: env.DB_PASSWORD
            value: ""
          - name: postgresql.enabled
            value: "false"
        valuesObject:
          env:
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-database
                  key: DB_PASSWORD
    
    - repoURL: git@github.com:soeguet/homelab.git
      targetRevision: HEAD
      path: apps/immich/base
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
